# ---- Zomslaught Configuration File ---- #
#
# ** Fright Night **
# 
# frightTimer: The time in seconds between each Fright Night. Defaults to 1200 (20 minutes).
frightTimer: 1200

# frightDuration: The time in seconds each Fright Night should last. Defaults to 60.
frightDuration: 60