name: Zomslaught
version: 0.2.0
main: com.SpectralVulpine.zomslaught.Zomslaught
commands:
  zomslaught:
    description: Primary Zomslaught command
    usage: /zomslaught [command]
    permission: zomslaught.basic
    permission-message: You do not have the power to control the Zomslaught...
permissions:
  zomslaught.admin:
    default: op
  zomslaught.basic:
    default: true